/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHL2Vm5HQW71N0So54IbivuWcsIzElW6w',
    appId: '1:596827048691:web:c15f8aa5ef087f828b0586',
    messagingSenderId: '596827048691',
    projectId: 'cachier-man-app',
    authDomain: 'cachier-man-app.firebaseapp.com',
    storageBucket: 'cachier-man-app.appspot.com',
    measurementId: 'G-Z9TTLNMF3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0BwMcJp4Nn0VGJRZkuDR50kj4xAwuEI',
    appId: '1:596827048691:android:0d1ada674656fa628b0586',
    messagingSenderId: '596827048691',
    projectId: 'cachier-man-app',
    storageBucket: 'cachier-man-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdMxcqEK1nujUFyTw98f2bBO8W6DAGjRY',
    appId: '1:596827048691:ios:f870557577cff4308b0586',
    messagingSenderId: '596827048691',
    projectId: 'cachier-man-app',
    storageBucket: 'cachier-man-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdMxcqEK1nujUFyTw98f2bBO8W6DAGjRY',
    appId: '1:596827048691:ios:6e489deed32135198b0586',
    messagingSenderId: '596827048691',
    projectId: 'cachier-man-app',
    storageBucket: 'cachier-man-app.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
*/
